# Generated by Django 5.2.17 on 2026-09-16 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text='Date when book was issued')),
                ('due_date', models.DateField(help_text='Date when book is due for return')),
                ('return_date', models.DateField(blank=True, help_text='Actual date when book was returned', null=True)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned')], default='Issued', help_text='Current status of the issue (Issued or Returned)', max_length=20)),
                ('book', models.ForeignKey(help_text='The book being issued', on_delete=django.db.models.deletion.RESTRICT, related_name='issues', to='books.book')),
                ('member', models.ForeignKey(help_text='The library member issuing the book', on_delete=django.db.models.deletion.RESTRICT, related_name='issues', to='members.member')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-id'],
            },
        ),
    ]
