# Generated by Django 5.2.17 on 2026-09-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('issues', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='book',
            field=models.ForeignKey(help_text='The book being issued', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='books.book'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='member',
            field=models.ForeignKey(help_text='The library member issuing the book', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='members.member'),
        ),
    ]
