# Generated by Django 5.2.17 on 2026-09-16 15:25

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the member', max_length=150)),
                ('email', models.EmailField(help_text='Unique valid email address', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Phone contact number', max_length=20, validators=[members.models.validate_phone_number])),
                ('department', models.CharField(help_text='Academic department or designation', max_length=100)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-id'],
            },
        ),
    ]
