# Generated by Django 5.2.17 on 2026-09-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the book', max_length=200)),
                ('author', models.CharField(help_text='Author of the book', max_length=200)),
                ('category', models.CharField(help_text='Category/genre of the book', max_length=100)),
                ('isbn', models.CharField(help_text='Unique ISBN number', max_length=30, unique=True)),
                ('quantity', models.IntegerField(default=1, help_text='Total number of copies in the library')),
                ('available_quantity', models.IntegerField(default=1, help_text='Number of copies currently available for issue')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-id'],
            },
        ),
    ]
